// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBB-BNr702n-7Cp03ZEDUOp_M3nQ9fT_M',
    appId: '1:423346607041:web:b4c4845f08ecde5dd5d540',
    messagingSenderId: '423346607041',
    projectId: 'educode-app-6729f',
    authDomain: 'educode-app-6729f.firebaseapp.com',
    storageBucket: 'educode-app-6729f.appspot.com',
    measurementId: 'G-FBLR93RZY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRc_niOtV-WN7Fi1AkDR9B5IGI7uPgTbA',
    appId: '1:423346607041:android:1be2d3983e404a36d5d540',
    messagingSenderId: '423346607041',
    projectId: 'educode-app-6729f',
    storageBucket: 'educode-app-6729f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1td5Bl_zPJNB7tAcpg7FGJfOF9W49AAw',
    appId: '1:423346607041:ios:667de0bc94095024d5d540',
    messagingSenderId: '423346607041',
    projectId: 'educode-app-6729f',
    storageBucket: 'educode-app-6729f.appspot.com',
    iosBundleId: 'com.example.educode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1td5Bl_zPJNB7tAcpg7FGJfOF9W49AAw',
    appId: '1:423346607041:ios:667de0bc94095024d5d540',
    messagingSenderId: '423346607041',
    projectId: 'educode-app-6729f',
    storageBucket: 'educode-app-6729f.appspot.com',
    iosBundleId: 'com.example.educode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBB-BNr702n-7Cp03ZEDUOp_M3nQ9fT_M',
    appId: '1:423346607041:web:3b5416fcfa296e0cd5d540',
    messagingSenderId: '423346607041',
    projectId: 'educode-app-6729f',
    authDomain: 'educode-app-6729f.firebaseapp.com',
    storageBucket: 'educode-app-6729f.appspot.com',
    measurementId: 'G-MQ33QG6R2K',
  );

}